<?xml version="1.0" encoding="UTF-8"?>
<!--
 SPDX-License-Identifier: EPL-1.0
 SPDX-FileCopyrightText: 2026 The Linux Foundation
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.opendaylight.testproject</groupId>
        <artifactId>testproject-aggregator</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>testproject-lib</artifactId>
    <packaging>jar</packaging>
    <name>ODL :: testproject :: ${project.artifactId}</name>
    <description>Implementation library for testproject</description>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>testproject-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
